DROP DATABASE IF EXISTS recipe_recommendations;
CREATE DATABASE recipe_recommendations;

\c recipe_recommendations;

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  email TEXT,
  name TEXT
);

CREATE TABLE food (
  id SERIAL PRIMARY KEY,
  name TEXT,
  prep_time TEXT,
  cook_time TEXT,
  total_time TEXT,
  servings TEXT,
  ingredients jsonb,
  directions jsonb,
  url TEXT
);

INSERT INTO food (name, prep_time, cook_time, total_time, servings, ingredients, directions, url) VALUES ('Grilled Salmon Burgers with Avocado Salsa', '20 mins', '8 mins', '28 mins', '4', '{ "ingredients": ["1 pound salmon fillet", "1/2 cup panko crumbs", "1 egg", "2 green onions chopped", "1/2 poblano pepper seeded and chopped", "1 tablespoon fresh lemon or lime juice", "1/2 teaspoon salt", "1/4 teaspoon pepper", "1 large ripe avocado - peeled seeded and chopped", "1/2 poblano pepper seeded and chopped", "2 green onions chopped", "1 tablespoon fresh lemon or lime juice", "1/4 teaspoon salt", "1/4 teaspoon pepper", "1/4 teaspoon salt"] }', '{ "directions": ["Skin and chop salmon fillet.", "Put in large bowl.", "Add panko, poblano,egg, green onion, lemon or lime juice, salt and pepper", "Mix well.", "(hint: make a cross on top of the salmon mixture before making into patties to ensure consistent size)", "Heat indoor grill pan or outdoor BBQ to medium high heat.", "Cook for about 4 minutes on each side until cooked through.", "For the Avocado Salsa: Combine all ingredients in medium bowl", "Top burgers with salsa. Serve with or without bun."] }', 'https://laughingspatula.com/grilled-salmon-burgers-with-avocado-salsa/#wprm-recipe-container-5339');

INSERT INTO food (name, prep_time, cook_time, total_time, servings, ingredients, directions, url) VALUES ('Skillet Mushroom Chicken and Quinoa', '10 mins', '15 mins', '30 mins', '4-6', '{ "ingredients": ["2 cups low-sodium chicken stock", "1 cup uncooked quinoa", "2 tablespoons extra-virgin olive oil, divided", "1 pound boneless, skinless chicken breasts, cut into 1-inch cubes", "1/2 teaspoon kosher salt, divided", "24 ounces cremini (baby bella) mushrooms", "1/4 teaspoon black pepper", "4 cloves garlic, minced", "1 tablespoon chopped fresh thyme", "1/4 cup freshly grated Parmesan, Gruyere, or similarly melty, nutty cheese, plus additional for serving"] }', '{ "directions": ["Bring 2 cups chicken stock to a gentle boil. Add the quinoa, return to boil, then reduce the heat to a simmer, cover, and let cook until most of the liquid is absorbed, 12 to 15 minutes. Remove from heat and let stand until the remaining liquid is absorbed, about 10 additional minutes. Fluff with a fork and set aside. (Note: This step may vary slightly depending upon your particular brand of quinoa. Be sure to check the directions.)", "Heat 1 tablespoon olive oil in a skillet over medium high. Sauté chicken with 1/4 teaspoon kosher salt until chicken is cooked through and no longer pink, about 4 to 6 minutes.", "Remove the chicken to a plate lined with paper towels, then with a paper towel gently wipe the skillet clean. Heat the remaining 1 tablespoon olive oil over medium high. Add the mushrooms, remaining 1/4 teaspoon salt, and black pepper. Cook, until the mushrooms begin to brown, about 3 minutes, stirring occasionally. Add the garlic and cook until the mushrooms are tender and have given up their liquid, 4 additional minutes. If there is a lot of remaining liquid in the pan, increase the heat and cook just until most of the liquid has evaporated, about 1 minute. Stir in the thyme, quinoa, chicken, and 1/4 cup Parmesan cheese. Serve warm, sprinkled with additional Parmesan."] }', 'https://www.wellplated.com/mushroom-chicken-and-quinoa-recipe/');

INSERT INTO food (name, prep_time, cook_time, total_time, servings, ingredients, directions, url) VALUES ('Black Bean Meatless Balls', '25 mins', '40 mins', '1 hr. 5 mins', '42 balls', '{ "ingredients": ["4 cups cooked black beans rinsed and well drained", "1 cup Bob’s Red Mill Gluten Free Quick Cooking Oats", "1 cup walnuts", "2 medium carrots", "1 medium onion", "1 tsp fennel seeds", "3 cloves garlic", "1 tsp paprika powder", "½ tbs kosher salt", "½ cup chopped parsley leaves"] }', '{ "directions": ["In a food processor, chop black beans to small chunks but do not puree. Transfer the chopped black beans into a large mixing bowl. Add oats and mix briefly. Set aside.", "Finely chop walnuts, carrots, onion, fennel seeds, garlic in food processor. Stir the mixture into the black bean-oat batter. Mix in the rest of ingredients and combine well.", "Cover the mixing bowl with lid or plastic wrap and let it chill in refrigerator for at least on hour.", "Remove the mixing bowl from refrigerator. Preheat oven at 350 ºF. Line the baking dish with parchment paper or lightly spray the baking dish with oil (use canola oil instead of olive oil). Scoop a golf ball size of batter and shape it to form a ball. Finish all the batter. It will yield approximately 42 balls. Bake for 20 minutes until one side is golden brown. Use a spatula to carefully flip the balls over. Bake for another 20 minutes until both sides are golden brown.", "Remove the balls from the baking dish and carefully transfer them onto a wire cooling rack for 5 minutes. Use as meatballs in other recipes if desired."] }', 'https://lightorangebean.com/black-bean-meatless-balls/');

INSERT INTO food (name, prep_time, cook_time, total_time, servings, ingredients, directions, url) VALUES ('Pear Salad With Dried Cherries And Candied Walnuts', '20 mins', '10 mins', '30 mins', '3', '{ "ingredients": ["1 heaping cup raw walnuts", "2 tsp olive or coconut oil", "1 Tbsp coconut sugar", "2 tsp maple syrup (or agave nectar)", "1 pinch sea salt", "1 pinch ground cinnamon", "1 pinch cayenne pepper (optional)", "1/4 cup balsamic vinegar", "1/4 cup extra virgin olive oil", "1 medium shallot, minced", "1 pinch each sea salt and black pepper", "1 6-ounce bag mixed greens (organic when possible)", "1 ripe Bosc or Bartlett Pear (thinly sliced lengthwise // stem and seeds removed)", "/4 cup dried cherries (or cranberries, though cherries are best!)"] }', '{ "directions": ["Preheat oven to 350 degrees F (176 C) and add raw walnuts to a bare or parchment-lined baking sheet.", "Once oven is preheated, toast walnuts for 7 minutes. Then remove from oven and add remaining ingredients directly to the walnuts (oil, coconut sugar, maple syrup, sea salt, cinnamon and cayenne - optional). Use a spatula to thoroughly toss/combine.", "Place back in oven and roast for another 4-6 minutes or until fragrant and golden brown. Set aside to cool.", "In the meantime, prepare dressing by adding all ingredients to a jar (or mixing bowl) and shaking vigorously (or whisking) to combine. Taste and adjust flavor as needed, adding more balsamic for acidity, salt or pepper for flavor balance, or olive oil for creaminess. Set aside.", "To serve, add greens, half of the sliced pear, dried cherries, and half of the roasted walnuts to a large mixing/serving bowl. Drizzle with a bit of the dressing and toss to combine.", "Plate and garnish with remaining pears and walnuts, and serve with remaining dressing. Best when fresh, though leftovers store separately in the refrigerator up to 3 days. Store walnuts well sealed at room temperature."] }', 'https://minimalistbaker.com/pear-salad-dried-cherries-candied-walnuts/');

INSERT INTO food (name, prep_time, cook_time, total_time, servings, ingredients, directions, url) VALUES ('Savory Oatmeal with Garlicky Kale', '5 mins', '20 mins', '25 mins', '2', '{ "ingredients":["1 cup steel cut oats", "1 1/2 cups vegetable broth", "1 1/2 cups water", "1/4 teaspoon salt (or to taste)", "1 bunch kale (roughly 4 cups chopped and packed)", "4 teaspoons olive oil (divided)", "4 cloves garlic", "2 large eggs (for frying)", "Red pepper flakes (for topping)"] }', '{ "directions": ["Combine vegetable broth and water in a pot. Bring to a simmer, add oats and salt, reduce heat, cover, and cook for roughly 15 minutes (add/subtract time for desired consistency of oats). Remove from heat and let sit for 5 minutes.", "Prepare the kale by removing the stems and cutting the leaves into 1/4 inch strips. As the oats are finishing, heat 2 teaspoons of olive oil in a large, wide pot. Add in the garlic, cooking for roughly a minute. Add the chopped kale and stir to coat with the garlic. Add in 1/4 cup of water, cover, and let kale cook for 5 minutes, stirring occasionally.", "Once done, remove kale from heat and transfer to a bowl. Add in the remaining 2 teaspoons of olive oil and fry the eggs to your liking.", "Assemble the bowls by dividing the oats into two bowls. Then top each bowl with garlicky kale and a fried egg."] }', 'https://naturallyella.com/savory-oatmeal-garlicky-kale/');